### ISSUE TITLE
pestpp-da notebooks

### ISSUE THREAD

**Issue by rhugman** [gmdsi/GMDSI_notebooks#40]
Hey @jtwhite79 ,

Starting to go through these to add some "words". It occurs to me that the da_prep notebook is all about converting an existing model/pest setup into DA-format. Do you think a more useful/generalizable tutorial would be to start from scratch rather than attempt to bastardize an existing setup? Would that not be a more common real-world scenario? This would require repeating PstFrom.

**Comment by jtwhite79** [comment]
@rhugman I'm no expert at getting setup for pestpp-da but my current approach is to modify a batch interface and model to sequential.  It's gross I know but this way we have the time varying pars and time varying obsvals queued up so that we can assign cycles to them.  But maybe all the other bs that is required outweighs this convenience...

**Comment by rhugman** [comment]
OK, fair enough. Leave as is then. So if you aren't the expert who is? :)
